### ISSUE TITLE
Allow the user to request rate by other than milliseconds

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/timely#104]
Currently (as of 0.0.3) the rate iterator only produces rates per millisecond.  I would be nice to change the Timely App GUI to allow the user to specify other (perhaps arbitrary) rate units.  This would also require passing an additional parameter down to the RateIterator.

**Comment by billoley** [comment]
Fixed as part of #207 by using time.ParseDuration in timely.go method convertTimelyQuery()

ParseDuration parses a duration string.
A duration string is a possibly signed sequence of
decimal numbers, each with optional fraction and a unit suffix,
such as "300ms", "-1.5h" or "2h45m".
Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
