### ISSUE TITLE
support OpenTSDB style aggregation

### ISSUE THREAD

**Issue by brianloss** [NationalSecurityAgency/timely#108]
OpenTSDB allows [aggregation](http://opentsdb.net/docs/build/html/user_guide/query/aggregators.html) of multiple series into a single one, as well as aggregation of values resulting from downsampled values. While Timely supports downsampling, it would be nice if it were also possible to combine multiple series into a single one via aggregation.

**Comment by dlmarion** [comment]
IIRC, aggregation into one time series may occur depending on the tags used in the query. For example, a query for a metric with:
  * no tags, will yield one time series result
  * tags with no wildcards, will yield one time series result
  * tags with wild cards, will yield one time series result for each match

I will double check this tomorrow.

**Comment by brianloss** [comment]
Agreed on your first and third points. If you query multiple singe tags with no wildcards, I believe you're right that you will also get one series. However, if you do a disjunction of discrete tag values you will still get multiple series.

Perhaps a better way to state it is for queries that do return more than one series, it would be nice to have the option to aggregate the multiple series together. The obvious use case would be for a Grafana graph with template variables, and metrics with a host tag. You might want to show a single value that is a combination of some metric from all hosts, but still be able to drill down and see the metric from an individual host.

**Comment by dlmarion** [comment]
This could be done on the client or server

**Comment by ivakegg** [comment]
Per the documentation, the order of overall operations is as follows:
    Filtering
    Grouping
    Downsampling
    Interpolation
    Aggregation
    Rate Conversion
    Functions
    Expressions

So we will adjust the down sampling to only aggregate within each timeseries.  This will essentially "align" the datapoints.  Then we will apply a separate aggregator that will aggregate the values at each timestamp.  We have decided that we will not do interpolation.

**Comment by ivakegg** [comment]
Found that when you "disable" the downsampling, that results in downsampling to the minute.  To really disable the downsampling, the default should be 1ms

**Comment by ivakegg** [comment]
Note that we are currently doing rate conversion before the downsampling.  We may need to fix that (separate ticket perhaps).
