### ISSUE TITLE
post delegation for guava

### ISSUE THREAD

**Issue by aamend** [NationalSecurityAgency/timely#114]
Still facing issues with post delgation classloading. My setup:
- accumulo: 1.8.0
- timely: 0.0.3

Following timely description... 

> Because Timely uses a newer version of Guava, you will need to configure a classloader for the Timely context, set it to use post-delegation, and then configure your tables to use the Timely context classloader. This can be done in the shell or in the accumulo-site.xml file.

I'm adding the following jars to ${ACCUMULO_HOME}/lib/ext

```
timely-client-0.0.3.jar
timely-server-0.0.3.jar
commons-lang3-3.1.jar
commons-collections4-4.1.jar
guava-19.0.jar
```

I'm using the following classloader context on accumulo

```
createnamespace timely
config -s general.vfs.context.classpath.timely=/usr/local/lib/timely/lib/guava-19.0.jar
config -s general.vfs.context.classpath.timely.delegation=post
config -ns timely -s table.classpath.context=timely
```

Still getting a tablet server exception that - I believe - is the guava version clash mentioned above. Could you please confirm syntax of my above settings? Something I'm missing here?

```
2016-11-05 01:39:59,687 [thrift.ProcessFunction] ERROR: Internal error processing startMultiScan
org.apache.thrift.TException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.common.base.Splitter.splitToList(Ljava/lang/CharSequence;)Ljava/util/List;
```

Thx for your support
A

**Comment by dlmarion** [comment]
Hey Antoine,

 If you have not done so, check out the classloader blog [entry] (https://github.com/NationalSecurityAgency/timely). Also, just to note, I don't think I have tried assigning the context to a namespace, it may work, but I usually assign it to the tables directly. If this does work for you, please let me know, it's good information.

Now, on to your problem. Did you specify the `general.vfs.classpaths` property in your accumulo-site file? This property activates the context classloader, without it the classloader behaves as it did in previous version of Accumulo where it will only load classes from the `lib` and `lib/ext` directory.

Try the following:
```
mkdir -p /usr/local/lib/accumulo-system-classpath /usr/local/lib/accumulo-timely-classpath
general.vfs.classpaths=file:///usr/local/lib/accumulo-system-classpath/.*.jar
general.vfs.context.classpath.timely=file:///usr/local/lib/accumulo-timely-classpath/.*.jar
general.vfs.context.classpath.timely.delegation=post
```
Copy the jars that you listed above into the `accumulo-timely-classpath` directory

**Comment by aamend** [comment]
Smashing! I confirm the `general.vfs.classpaths` was missing.
Works perfectly
