### ISSUE TITLE
Test Timely-App integration with Grafana 4

### ISSUE THREAD

**Issue by dlmarion** [NationalSecurityAgency/timely#123]

**Comment by alerman** [comment]
Opened PR https://github.com/NationalSecurityAgency/timely/pull/147 to address issues with newer lodash version in Grafana 4.

**Comment by dlmarion** [comment]
@alerman - thanks for this. I will pull it down and test it out.

**Comment by dlmarion** [comment]
Finding other functions that no longer exist, ._pairs for example
