### ISSUE TITLE
Modify Timely App datasource to support Grafana 4 alerting

### ISSUE THREAD

**Issue by dlmarion** [NationalSecurityAgency/timely#152]
If you try to use alerting in Grafana 4 with the 0.0.5 Timely app, you will get an error saying that the datasource does not support a method. Need to implement that method.

**Comment by billoley** [comment]
This is not possible until Grafana implements server-side plugins.  A workaround is to use aOpenTSDB datasource or maybe to fork grafana and add a Timely datasource.  Closing for now.
