### ISSUE TITLE
Variable length age-off for metrics

### ISSUE THREAD

**Issue by drewfarris** [NationalSecurityAgency/timely#16]
Currently, all metrics have a uniform age-off established via `timely.metric.age.off.days`. We might want to retain some metrics for a longer time. Opening this issue to discuss how we might implement this.

1) separate table sets / namespaces, e.g: metrics written to sevenday.timely and monthly.timely will age off at different rates - use options like `timely.metric.ageoff.seveday.days=7 and timely.table.namespaces=sevenday,monthly`

2) store all metrics in the same tables and bake the age-off into the auths with a top level alternation: `( Ao7d | A & B & C )`

3) Other ideas?

**Comment by dlmarion** [comment]
"For example, keep granular metrics for 7 days, then roll up to hourly/daily level. The granular metrics have the timestamp in the key and a double in the value. The summarized metric could contain a list of time offset / value pairs, offset being the offset from the key timestamp."

Tested this approach in #64. Going to pass on summarizing and compacting data for now. Talked with @drewfarris about his original description and I think providing a default ageoff value, and a per metric age-off will be sufficient for now.

**Comment by dlmarion** [comment]
Need to change how the Configuration works such that it supports a map of metric name to age off value.
