### ISSUE TITLE
Create tablet balancer for the metrics table

### ISSUE THREAD

**Issue by dlmarion** [NationalSecurityAgency/timely#2]
If you split the metrics table by metric name, then the amount of data being sent to the tservers may be unbalanced. For example, if you have a 4 core cpu, then you will generate 4x the number of mutations for the sys.cpu.user split then you would for sys.load.relative which will have only 1 value per server. Understanding the distribution of the data should allow us to create a balancer that will assign tablets to tserver such that each tserver is getting similar amounts of mutations per unit time.

**Comment by billoley** [comment]
This is OBE since adding the timestamp (rounded down to the hour) to the row.  This change was implemented to enable skipping lots of entries with colFamilies that were not of interest or duplicative.

The metrics table rows will now split when the split threshold is reached.
