### ISSUE TITLE
Tutorial for Java client

### ISSUE THREAD

**Issue by hbs** [NationalSecurityAgency/timely#202]
I am in the process of adding support for Timely to the [Warp 10 ](https://warp10.io) Analytics Engine to allow the manipulation of data stored in Timely using [WarpScript](https://warp10.io/content/03_Documentation/04_WarpScript/01_Concepts).

I could not find a tutorial on how the Java client should be used. Is there some page that documents this process or should the code be digged into?

**Comment by billoley** [comment]
This is way late..... but I would recommend looking at the code

**Comment by hbs** [comment]
Way late indeed :-) Will do then!
