### ISSUE TITLE
Create Timely data source for Grafana

### ISSUE THREAD

**Issue by dlmarion** [NationalSecurityAgency/timely#21]
We are diverging from the existing OpenTSDB datasource in Grafana. We need to create our own plugin.

**Comment by dlmarion** [comment]
Regarding Swagger, we might want to wait until [this] (http://www.zdnet.com/article/severe-swagger-vulnerability-compromises-nodejs-php-java/) is fixed.

**Comment by klucar** [comment]
No. We won't use their code generation. Swagger is just a documentation
format.

**Comment by dlmarion** [comment]
Closing as creating the datasource is covered by creating the app in #33
