### ISSUE TITLE
Develop embedded site for Timely

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#22]
We should serve up some kind of UI for Timely from the server. For instance the api/metrics endpoint should only return JSON, and some embedded site should use Javascript to fetch the JSON and render it to HTML for the user.

**Comment by dlmarion** [comment]
@klucar put your web resources into src/main/resources/webapp. You should be able to retrieve them from /webapp/<file>.

**Comment by klucar** [comment]
cool. think we should redirect / to /webapp/

**Comment by dlmarion** [comment]
Easily changed once we figure out how its going to work.

**Comment by klucar** [comment]
I've started on the grafana datasource. Using the latest grafana, I am making Timely a Grafana "app" so it can show the api/metrics data inside Grafana. Looking at this, it should be possible to make the pages inside Grafana be reused and served outside grafana, since a grafana app is just an Angular partial rendered in Grafana. (i.e. we could just render the same partial when not using Grafana)
