### ISSUE TITLE
Creating my SSL materials in Timely

### ISSUE THREAD

**Issue by Montana** [NationalSecurityAgency/timely#228]
When I try and generate a certificate signing request (CSR) with our Timely private key running:

```bash
openssl req -new -key timely.key -sha256 -nodes -subj '/C=US/ST=Confusion/L=Here/O=Timely/OU=Server/CN=localhost/emailAddress=noreply@localhost/subjectAltName=DNS.1=127.0.0.1' > timely.csr
```

I then went ahead and used the CSR and the CA to create a certificate for the server (a reply to the CSR):

```bash
openssl x509 -req -in timely.csr -CA CA.pem -CAkey CA.key -CAcreateserial -out timely.crt `-days 365`.
```

Convert the private key to pkcs#8 format (still iffy):

```bash
openssl pkcs8 -topk8 -inform PEM -outform PEM -in timely.key -out timely-pkcs8.key
```

**Comment by ctubbsii** [comment]
This doesn't look like a valid issue for this project, and no question or problem is being reported.
