### ISSUE TITLE
Binary is not portable

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#28]
I think this is a weird case, but I compiled on OS X, and ran on Linux. Since I compiled on OS X the netty jar doesn't have the correct native netty library but the JVM reports Linux as the OS so timely tries to use the native netty NioEventLoopGroup, instead of the epoll ones.

I think we should allow an option to force epoll over native from some config option. Or we could do netty mode options as epoll,native,auto defaulting to auto so it is the current behavior.

**Comment by dlmarion** [comment]
The os-maven-plugin creates a set of maven properties based on the architecture of the machine on which you are building the project. The server pom file uses the `os.detected.classifier` property to grab the correct version of the netty-tcnative dependency for your machine. You should be able to override the value of the property on the command line like so: `mvn clean package -Dos.detected.classifier=???`, where ??? is one of the correct classifiers.

**Comment by klucar** [comment]
I'll give it a shot. Perhaps we should make the build always use Linux and
have the Server.java code just do epoll for non-Linux. Supporting OS X for
production isn't really a requirement in my mind.

**Comment by dlmarion** [comment]
Do you have a stack trace?

**Comment by dlmarion** [comment]
Maybe we just need to tweak the logic in Server.useEpoll(). I think the only code that uses a native library though is the OpenSSL code. Two different issues, so I am a little confused as to which one you are hitting.

**Comment by klucar** [comment]
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-linux-x86_64, netty-tcnative-linux-x86_64-fedora, netty-tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:167)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:78)
	... 9 more

**Comment by dlmarion** [comment]
Ok, I don't think this is an epoll issue, and I think it is directly related to the `os.detected.classifier` build property.

**Comment by dlmarion** [comment]
Timely uses the (netty-tcnative) [http://netty.io/wiki/forked-tomcat-native.html] module to provide native access to OpenSSL. The correct version of the artifact is downloaded during the build. If you are building for a different platform, then you can override the classifier by specifying the `os.detected.classifier` property on the Maven command line. See the netty-tcnative wiki for more information.

**Comment by dlmarion** [comment]
I'll update the wiki with the text above.
