### ISSUE TITLE
TCP put isn't secure

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#29]
Currently we don't authenticate servers/processes/anything sending us data. Open a socket and timely will record what you send. 

Perhaps we want to fix that, but there's many ways to do this and more implications.

**Comment by dlmarion** [comment]
The current model supports anyone creating a TCP connection and sending data to Timely. This could be locked down to known producers using iptables or something like it. Agreed that there are multiple ways to solve this but I am going to suggest closing this until we have some use cases defined/requested that we need to support.

**Comment by klucar** [comment]
Agreed, there is no requirement for this right now. I would suggest that a secure interface would be to implement an HTTP interface for PUT.
