### ISSUE TITLE
Query with no tags specified just returns first series.

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#30]
Noticed this when using the insert-test-data program. I created charts for each sys.cpu0.user (host=*), one aggregated by rack (rack=*), which came out fine. Then I created one without any tags and it returned the data for host=r01n01 only. My thought was this should aggregate over all the data to be consistent. This could be computationally expensive and actually be requested a lot when people are creating new charts, so perhaps a special tag should explicitly indicate to aggregate everything (tags=none ?)

In the attached image aggregators are sums. The first chart has peaks around 100, second has peaks around 200, the third should have peaks around 400, but is actually just r01n01 data.

<img width="1316" alt="screen shot 2016-06-28 at 6 45 31 am" src="https://cloud.githubusercontent.com/assets/631840/16413000/2ad2e82a-3cfd-11e6-96fb-72a105a686a0.png">

**Comment by dlmarion** [comment]
The current behavior (in DataStoreImpl.setQueryColumns) is to use the first tag K,V found in the meta table for the metric if no tags are specified in the query. We can change that pretty easily, we just need to figure out how we want it to behave.

**Comment by klucar** [comment]
That's what I figured. Again, my main worry is that if no tags defaulted aggregate everything, making dashboards would kick off large scans you don't actually want. I think some special tag would work, or perhaps send in an option once #21 is up.

**Comment by klucar** [comment]
Also, right now there's no way to specify a cumulative aggregation like I was trying.

**Comment by dlmarion** [comment]
So, we assume that there is a single set of tags for a metric. For example, that all `sys.cpu.user` metrics will have the same set of tags (host, rack). Because we store N (2 in this example) copies of the metric, we only need to return the set of metrics that match of the tags (host or rack). When no tags are present in the query we grab the first tag name from the meta table for the metric, then expand the query to the metric, the tag name, and all known tag values. This approach does break down if you have disjoint sets of tags for a metric.

**Comment by klucar** [comment]
I think the case I showed you today using the ingest test data script
doesn't have a disjoint set of tags. Or I'm not understanding what a
disjoint set of tags is.

**Comment by dlmarion** [comment]
I added a test (which initially failed, now succeeds) to confirm that if no tags are present in the query, it will use all of the values for the first tag encountered in the meta table for the metric.

**Comment by klucar** [comment]
Verified latest master 42d31efff88dc952adeaf2f12a86a83305e9b6ac works as expected now. All metrics were set to sum aggregators, and multi-metric charts were stacked. All 3 charts are the same now, showing that the 3rd chart is the correct aggregation over the host tag.

![screen shot 2016-06-29 at 2 26 01 pm](https://cloud.githubusercontent.com/assets/631840/16463876/c5d849d8-3e05-11e6-87f0-42ff9a23722d.png)
