### ISSUE TITLE
Create toplevel endpoint that returns version info

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#38]
Grafana datasource requires a way to test the datasource is working. Currently the OpenTSDB datasource does a suggest query for 'cpu'. My thought is to have an endpoint (/api ?) that returns a 200 OK, and maybe some timely info like version, etc.

My initial thought was to use the api/metrics endpoint but this sometimes takes a bit to return.

**Comment by klucar** [comment]
perhaps api/aggregators is sufficient for this.

**Comment by dlmarion** [comment]
api/aggregators should be fast and good enough for now.

**Comment by klucar** [comment]
does that go through the same SSL path?

**Comment by dlmarion** [comment]
Yes

**Comment by dlmarion** [comment]
Will address in #36.
