### ISSUE TITLE
file server is serving filesystem at toplevel URL

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#39]
while testing I found that https://localhost:54322/ displays the filesystem. Probably a mis-wiring in the static file server somehow. This was seen in the docker-compose setup.

![screen shot 2016-07-08 at 12 32 45 pm](https://cloud.githubusercontent.com/assets/631840/16694430/388f90d6-4508-11e6-9bbe-6f68714c2211.png)

**Comment by dlmarion** [comment]
Interesting, in my testing the root listed the bin directory. Definitely need to scope it just to the webapp directory

**Comment by dlmarion** [comment]
I fixed this during the api-rewrite. Tested locally on master just now and it will only serve up files from /webapp. When we have a favicon.ico file, we will need to modify this to serve it up.
