### ISSUE TITLE
certs readme

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#48]
Create a readme with how to create a CA and all the certs needed to run everything in https, including client cert in browser and interface to authenticate user cert.

**Comment by dlmarion** [comment]
Might be able to point to this: http://accumulo.apache.org/1.7/accumulo_user_manual#_generating_ssl_material_using_openssl

**Comment by klucar** [comment]
That's probably good, with some words about timely properties to point to what files.

**Comment by ctubbsii** [comment]
There's also a blog which might help here: https://blogs.apache.org/accumulo/entry/generating_keystores_for_configuring_accumulo

In general, there's tons of documentation out there for generating and using x509 certificates. It might be best to defer to those dedicated documentation, and make the documentation here just focus on how they're used in Timely.

I wouldn't want users to be overloaded with a whole "openssl HOWTO" and the details of how to use certs in Timely get lost in the noise, nor would I want this project/community to suffer from bloat as it tries to anticipate and solve all conceivable user issues, like how to generate certificates.

**Comment by dlmarion** [comment]
Agreed. I didn't document much, basically the required formats of the files to secure Timely and Grafana. Maybe we just need a few more sentences and a link to another site.

**Comment by klucar** [comment]
We really just need to highlight the different security modes.
Insecure, Anonymous, user/pass, cert, etc

**Comment by dlmarion** [comment]
Added in #46
