### ISSUE TITLE
Test grafana timely-app in actual deployment

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#50]
Most of the development and testing of the grafana app has been done using docker and localhost. We need to test the app using different hosts for everything to ensure we're not getting success because the localhost hostname is everywhere.

perhaps doing this with #47 makes sense.

**Comment by dlyle65535** [comment]
Is anyone working this? I'd like to get involved and this looks like a good place to start.

**Comment by dlmarion** [comment]
@dlyle65535: @klucar has done some testing during timely app development. I'd like to get the PR reviewed and the grafana branch merged to master. At that point, I think we will be ready to begin testing for the 0.0.2 release. The branch might be merged in a day or so. If you are looking to get involved, having an outsider review the new documention would be great. Let me know if you are interested and I can you set up.

**Comment by klucar** [comment]
@dlmarion We should put our roadmap in the README so others know our plans.

**Comment by dlmarion** [comment]
@klucar I have attached milestones to the issues, we could also put dates on the milestones. If we need more, we could add a notional schedule and checklist on the wiki.

**Comment by klucar** [comment]
@dlyle65535 We'd appreciate the testing! I have done a bunch of testing but it was mostly in the docker-compose setup, so a test on a real multi-host setup would be great. Just walking through the docs and making sure you can deploy everything is great too. Feel free to reach out and we can hop on chat or whatever if you get stuck.

**Comment by dlyle65535** [comment]
@dlmarion @klucar Absolutely interested. I have some time over the weekend, so if the branch gets merged, the timing seems perfect.

**Comment by dlmarion** [comment]
@dlyle65535 early documentation is up at http://nationalsecurityagency.github.io/timely/

**Comment by dlmarion** [comment]
@dlyle65535 and grafana has been merged into the master branch. You should be ok to begin testing.

**Comment by klucar** [comment]
@dlyle65535 get a chance to do anything with it this weekend?

**Comment by dlmarion** [comment]
Several people have tested this locally, in and out of Docker containers. I'm willing to close this and fix remaining issues in the next release. @klucar @drewfarris : thoughts?

**Comment by klucar** [comment]
:rocket: ship it

**Comment by dlyle65535** [comment]
@klucar - I did, but have some basic sanity issues in my environment. Glad others had a chance to as well. I'll keep chipping away and be ready for next time.

**Comment by dlmarion** [comment]
@dlyle65535 : let us know if we can help with anything.
