### ISSUE TITLE
Metrics Browser Dies if Datasource can't be contacted

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#60]
When multiple datasources are defined, if the user's browser can't resolve a datasource address,  metrics fail to be drawn. Need to catch this problem and just try the next datasource.

**Comment by dlmarion** [comment]
@klucar Is this still an issue? If so, I'm going to punt it to the next release.

**Comment by billoley** [comment]
Closing with re-write of the datasource plugin in #207 
Selection of datasource is a Grafana issue in any case
