### ISSUE TITLE
Investigate Proxy Access

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#61]
OpenTSDB had the ability for the Grafana server to proxy the request to the database instead of the request coming straight from the browser. This would allow us to expose the server running Grafana without exposing the server running timely. It was disabled to get all the cookie/security/login stuff working but now that we understand that part better, perhaps the proxy can work.

**Comment by billoley** [comment]
Requires grafana server-side plugin capability which is not implemented yet.
