### ISSUE TITLE
Create options to allow timely to only serve queries or ingest

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#62]
Having one server do it all is convenient, but in production it would be nice to be able to load balance query and ingest separately. You could also manage what ports get exposed easier.

**Comment by dlmarion** [comment]
Inserting data can be performed across all protocols (tcp, http, websocket). Making a Timely server only support read operations, or only support write operations, would likely have to be done in the DataSource class.

**Comment by billoley** [comment]
This conflicts with the idea of in-memory caching.  Closing.
