### ISSUE TITLE
change ssl configuration option

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#63]
timely.ssl.use.generated.keypair seems prone to error. Suggest enabling ssl with:

timely.ssl.enable=true

**Comment by dlmarion** [comment]
SSL is always enabled, either via JDK or OpenSSL. The `timely.ssl.use.generated.keypair` option is useful for testing. What's the problem you ran into?

**Comment by klucar** [comment]
Fixed with: 019c5789ce9c1da1fa09bcd452aa8a3206713110
