### ISSUE TITLE
Change Downsample calculation on TabletServers, remove interpolation in Timely

### ISSUE THREAD

**Issue by dlmarion** [NationalSecurityAgency/timely#91]
The Downsample iterator creates an array of size `(query end - query start) / (downsample period + 1)`. By precreating this structure, then populating the buckets as we run across keys, we potentially end up with a lot of buckets with no samples (thus a value of zero). Then, we return the entire array back to the Timely server.

When the Timely server receives the downsample array from the tablet servers, it merges arrays received for the same time series (assuming that a time series could be split across multiple tablets), and then interpolates missing values.

We could save time and space if we changed how this is done. We could, for example, add new buckets to the downsample by evaluating the current key in the downsample iterator and evaluating the timestamp to the period of the last bucket. If this key does not fit into that bucket, create a new one starting at the appropriate start time. Additionally, we could stop interpolating missing values and let the U/I or user do that (Grafana will do this).

**Comment by klucar** [comment]
:thumbsup:
