### ISSUE TITLE
Support true rate query

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#94]
We need to decide how to handle rate queries. Right now, we have a digital filter iterator that will combine samples using a filter. To get a running difference (derivative) a filter of (-1,1) suffices. The problem arises in that this assumes the two samples are perfectly periodic and regular (e.g. they're always exactly 1 minute apart) A true rate would divide the difference by the time gap between the two samples. This may not be necessary in reality. The rate from a simple derivative may have noise associated with sampling times, but that error should truly be noise compared to what the query is trying to expose. 

If a true rate is calculated, the downsampling must be handled correctly also. There is a link in the code to the correct way to do this, taken from collectd website.

**Comment by dlmarion** [comment]
The calculation that you are referring to is for converting a rate into a counter with max and reset values.
